server:
  port: 19010
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/templlo
    username: root
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_schema: users
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: templlo123456789templlo123456789templlo123456789templlo123456789templlo123456789templlo123456789

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.sql: DEBUG