server:
  port: 19010
spring:
  application:
    name: user-service
#  datasource:
#    url: jdbc:postgresql://localhost:5432/users
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
    register-with-eureka: true
    fetch-registry: true