⚙ Setting:
  - setting

✨ Feature:
  - feature
  - Feature  # 대소문자 구분 없이 처리 가능

🌏 Deploy:
  - deploy

🎨 Html&css:
  - html
  - css

🐞 BugFix:
  - bugfix

📃 Docs:
  - docs

🔨 Refactor:
  - refactor

✅ Test:
  - test

🙋‍♂️ Question:
  - question

🥰 Accessibility:
  - accessibility

💻 CrossBrowsing:
  - crossbrowsing

📬 API:
  - api
