server:
  port: 19050

spring:
  application:
    name: promotion-service

  datasource:
    url: jdbc:postgresql://localhost:5432/templlo
    username: root
    password: 12341234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

cloud:
  gateway:
    discovery:
      locator:
        enabled: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
