server:
  port: 19091

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**, /api/users/**
        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/api/reviews/**
        - id: temple-service
          uri: lb://temple-service
          predicates:
            - Path=/api/temples/**
        - id: program-service
          uri: lb://program-service
          predicates:
            - Path=/api/programs/**
        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/api/reservations/**
        - id: promotion-service
          uri: lb://promotion-service
          predicates:
            - Path=/api/promotions/**
            - Path=/api/coupons/**
      discovery:
        locator:
          enabled: true

jwt:
  secret: ${JWT_SECRET_KEY}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

logging:
  level:
    org.springframework.web: DEBUG