server:
  port: 19015
spring:
  application:
    name: review-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
    register-with-eureka: true
    fetch-registry: true