name: Run Test 🚀

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'gateway/**'
      - 'server/**'
      - 'com.templlo.service.user/**'
      - 'com.templlo.service.promotion/**'
      - 'com.templlo.service.reservation/**'
      - 'com.templlo.service.temple/**'
      - 'com.templlo.service.program/**'
      - 'com.templlo.service.review/**'
  push:
    branches: [ "main" ]
    paths:
      - 'gateway/**'
      - 'server/**'
      - 'com.templlo.service.user/**'
      - 'com.templlo.service.promotion/**'
      - 'com.templlo.service.reservation/**'
      - 'com.templlo.service.temple/**'
      - 'com.templlo.service.program/**'
      - 'com.templlo.service.review/**'

jobs:
  build:
    name: Build and Test Services
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # 하나의 서비스 실패해도 다른 서비스 계속 빌드
      matrix:
        service:
          - gateway
          - server
          - com.templlo.service.user
          - com.templlo.service.promotion
          - com.templlo.service.reservation
          - com.templlo.service.temple
          - com.templlo.service.program
          - com.templlo.service.review

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Build and Test
        working-directory: ${{ matrix.service }}
        run: |
          echo "Building ${{ matrix.service }}"
          chmod +x gradlew
          ./gradlew clean build
