name: Run Test 🚀

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'gateway/**'
      - 'server/**'
      - 'com.templlo.service.user/**'
      - 'com.templlo.service.promotion/**'
      - 'com.templlo.service.reservation/**'
      - 'com.templlo.service.temple/**'
      - 'com.templlo.service.program/**'
      - 'com.templlo.service.review/**'
  push:
    branches: [ "main" ]
    paths:
      - 'gateway/**'
      - 'server/**'
      - 'com.templlo.service.user/**'
      - 'com.templlo.service.promotion/**'
      - 'com.templlo.service.reservation/**'
      - 'com.templlo.service.temple/**'
      - 'com.templlo.service.program/**'
      - 'com.templlo.service.review/**'

jobs:
  build:
    name: Build Jar
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # STEP1. 빌드
      - name: Build with Gradle
        id: build
        run: ./gradlew clean build -x test

      # STEP2. 테스트코드 실행
      - name: Run Tests
        id: test
        run: ./gradlew test
