name: Issue and PR Labeler
on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      # Step for labeling issues based on title or body content
      - name: Label Issues Based on Title or Body
        if: ${{ github.event_name == 'issues' }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: '.github/labeler.yml'

      # Step for labeling pull requests based on title or body content
      - name: Label Pull Requests Based on Title or Body
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: '.github/labeler.yml'
