name: Labeler
on:
  pull_request_target:
    types: [opened, synchronize]
  issues:
    types: [opened, edited]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - name: Add Label to Pull Requests
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Add Label to Issues
        if: ${{ github.event_name == 'issues' }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          labels: |
            ${{ github.event.issue.title }}
