name: Issue and PR Labeler
on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - name: Label Issues and PRs Based on Title or Body
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            ⚙ Setting:
              - setting
            ✨ Feature:
              - feature
            🌏 Deploy:
              - deploy
            🎨 Html&css:
              - html
              - css
            🐞 BugFix:
              - bugfix
            📃 Docs:
              - docs
            🔨 Refactor:
              - refactor
            ✅ Test:
              - test
            🙋‍♂️ Question:
              - question
            🥰 Accessibility:
              - accessibility
            💻 CrossBrowsing:
              - crossbrowsing
            📬 API:
              - api
