name: Simple Labeler
on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, ready_for_review]

jobs:
  simple-labeler:
    runs-on: ubuntu-latest
    steps:
      # 코드 체크아웃
      - name: Checkout Code
        uses: actions/checkout@v3

      # 디버깅: 이벤트 데이터 출력
      - name: Debug Logging
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Event Payload: ${{ toJSON(github.event) }}"
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Body: ${{ github.event.issue.body }}"

      # 라벨러 파일 확인
      - name: Check Labeler File
        run: ls -al .github

      # 라벨러 파일 내용 확인
      - name: Debug Labeler
        run: |
          echo "Running Labeler with Configuration"
          cat .github/labeler.yml

      # Issues 이벤트 처리
      - name: Setup Labels for Issues
        if: ${{ github.event_name == 'issues' }}
        uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml

      # Pull Requests 이벤트 처리
      - name: Setup Labels for Pull Requests
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
